# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sb_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostinfo',
            options={},
        ),
    ]
