# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sb_admin', '0002_auto_20171112_0529'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hostinfo',
            table=None,
        ),
    ]
