# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sb_admin', '0004_auto_20171126_1433'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hostinfo',
            table='hostinfo',
        ),
    ]
